"""Unit tests for the reject/regenerate LangGraph loop.

Mocks ``generate_draft_response`` directly (not the Ollama client) --
draft_graph.py's job is the graph's control flow (pause/resume,
attempt counting, routing), not draft generation itself, which already
has its own tests in test_response_draft.py.
"""

from __future__ import annotations

from unittest.mock import patch

import pytest
from langgraph.types import Command, RunnableConfig

from aurapulse.classifier import ClassificationError
from aurapulse.draft_graph import (
    MAX_ATTEMPTS,
    build_draft_graph,
    draft_outcome,
    initial_state,
)
from aurapulse.schemas import (
    Aspect,
    AspectMention,
    DraftResponse,
    ReviewAnalysis,
    Sentiment,
)


def _analysis() -> ReviewAnalysis:
    return ReviewAnalysis(
        review_id="r1",
        business_id="b1",
        overall_sentiment=Sentiment.NEGATIVE,
        aspects=[AspectMention(aspect=Aspect.WAIT_TIME, sentiment=Sentiment.NEGATIVE)],
        severity_flag=False,
    )


def _draft(text: str) -> DraftResponse:
    return DraftResponse(review_id="r1", business_id="b1", draft_text=text)


def _config(thread_id: str) -> RunnableConfig:
    return RunnableConfig(configurable={"thread_id": thread_id})


# --- draft_outcome (pure helper) ---


def test_draft_outcome_pending_by_default() -> None:
    assert draft_outcome({"approved": False, "attempt": 1, "max_attempts": 3}) == "pending"


def test_draft_outcome_approved() -> None:
    assert draft_outcome({"approved": True, "attempt": 1, "max_attempts": 3}) == "approved"


def test_draft_outcome_needs_human_rewrite_when_attempts_exhausted() -> None:
    assert draft_outcome({"approved": False, "attempt": 3, "max_attempts": 3}) == "needs_human_rewrite"


# --- initial_state ---


def test_initial_state_defaults() -> None:
    state = initial_state("r1", "b1", "text", _analysis())
    assert state["attempt"] == 0
    assert state["approved"] is False
    assert state["draft_text"] is None
    assert state["max_attempts"] == MAX_ATTEMPTS


# --- graph control flow ---


@patch("aurapulse.draft_graph.generate_draft_response")
def test_first_invoke_generates_a_draft_and_pauses(mock_generate) -> None:
    mock_generate.return_value = _draft("first draft")
    graph = build_draft_graph()

    result = graph.invoke(initial_state("r1", "b1", "text", _analysis()), config=_config("t1"))

    assert result["draft_text"] == "first draft"
    assert result["attempt"] == 1
    assert "__interrupt__" in result
    mock_generate.assert_called_once()
    assert mock_generate.call_args.kwargs["feedback"] is None


@patch("aurapulse.draft_graph.generate_draft_response")
def test_approve_ends_the_loop(mock_generate) -> None:
    mock_generate.return_value = _draft("first draft")
    graph = build_draft_graph()
    config = _config("t2")
    graph.invoke(initial_state("r1", "b1", "text", _analysis()), config=config)

    result = graph.invoke(Command(resume={"approved": True, "feedback": None}), config=config)

    assert "__interrupt__" not in result
    assert draft_outcome(result) == "approved"
    mock_generate.assert_called_once()


@patch("aurapulse.draft_graph.generate_draft_response")
def test_reject_with_attempts_remaining_regenerates_with_feedback(mock_generate) -> None:
    mock_generate.side_effect = [_draft("first draft"), _draft("second draft")]
    graph = build_draft_graph()
    config = _config("t3")
    graph.invoke(initial_state("r1", "b1", "text", _analysis()), config=config)

    result = graph.invoke(Command(resume={"approved": False, "feedback": "too generic"}), config=config)

    assert result["draft_text"] == "second draft"
    assert result["attempt"] == 2
    assert "__interrupt__" in result
    assert draft_outcome(result) == "pending"
    assert mock_generate.call_count == 2
    assert mock_generate.call_args.kwargs["feedback"] == "too generic"


@patch("aurapulse.draft_graph.generate_draft_response")
def test_repeated_rejection_ends_in_needs_human_rewrite_after_max_attempts(mock_generate) -> None:
    mock_generate.side_effect = [_draft(f"draft v{i}") for i in range(1, MAX_ATTEMPTS + 1)]
    graph = build_draft_graph()
    config = _config("t4")
    graph.invoke(initial_state("r1", "b1", "text", _analysis()), config=config)

    # attempt 1 was generated by the initial invoke() above; each reject either
    # regenerates (attempt < max) or ends the loop (attempt == max) -- reaching
    # "needs_human_rewrite" takes MAX_ATTEMPTS rejects in total, not MAX_ATTEMPTS - 1,
    # since the terminating reject itself doesn't generate a new draft.
    result = None
    for _ in range(MAX_ATTEMPTS):
        result = graph.invoke(Command(resume={"approved": False, "feedback": "still not right"}), config=config)

    assert result is not None
    assert "__interrupt__" not in result
    assert result["attempt"] == MAX_ATTEMPTS
    assert draft_outcome(result) == "needs_human_rewrite"
    assert mock_generate.call_count == MAX_ATTEMPTS


@patch("aurapulse.draft_graph.generate_draft_response")
def test_generation_failure_propagates_instead_of_being_swallowed(mock_generate) -> None:
    mock_generate.side_effect = ClassificationError("Ollama unreachable")
    graph = build_draft_graph()

    with pytest.raises(ClassificationError):
        graph.invoke(initial_state("r1", "b1", "text", _analysis()), config=_config("t5"))
